version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: backend_container
    ports:
      - "5003 :5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydb   
      - PORT=5000
    depends_on:
      - mongo

volumes:
  mongo-data:
